### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by Coltigo**
I added a link to the google doc, removed Chastify because he is longer on the team, and some other minor updates for the front page.

### CODE REVIEW

**Review by caughtquick — APPROVED** [review]
This looks fine to me 👍

**Comment by thewarsawpakt** [comment]
Does everyone have write to the doc? If so, I'd like to figure out how we can change that because it's a pretty dangerous permission to grant.

**Comment by caughtquick** [comment]
Yeah everyone has write to the doc

**Comment by mugman174** [comment]
> I added a link to the google doc, removed Chastify because he is longer on the team, and some other minor updates for the front page.

Weird I don't see any of that stuff :thinking:

**Comment by Coltigo** [comment]
Ya everyone would have rights to the doc but pakt said it didn't matter to him iirc

**Review by DanKGooGLy — APPROVED** [review]

**Comment by caughtquick** [comment]
@DanKGooGLy close this PR, coltigo needs to fix some stuff then we can make a new one, i can't close the pr cause i don't have write

**Comment by mugman174** [comment]
Coltigo
Ok you added yourself to the site but what else?

**Comment by DanKGooGLy** [comment]
ok

**Pull request closed without merging**
