### PR TITLE
Fix 404 page missing image

### PR DESCRIPTION
**Pull request by 1ctinus**

### CODE REVIEW

**Comment by mugman174** [comment]
imma check this

**Comment by 1ctinus** [comment]
it should also be absolute pathing i believe, starting with /

**Comment by mugman174** [comment]
screenshot of test
yep it seems good

**Review by catcosmicice — APPROVED** [review]
yeah 1ct's right

**Comment by mugman174** [comment]
imma fix the rest of the css

**Comment by catcosmicice** [comment]
> yeah 1ct's right

late reply, sorry lol

**Pull request merged**
