### PR TITLE
Switch to LESS

### PR DESCRIPTION
**Pull request by DanKGooGLy**
Switch from SASS to LESS, a probably more efficient expansion of CSS,

### CODE REVIEW

**Comment by thewarsawpakt** [comment]
Can I get some benchmarks?

**Comment by mugman174** [comment]
Ok I’m gonna test

**Comment by mugman174** [comment]
Uhh I can’t really benchmark bc I’m on mobile but the site looks fine

**Comment by thewarsawpakt** [comment]
Make sure to pull on the beta site, too.

**Comment by mugman174** [comment]
K will do

**Pull request merged**
