### PR TITLE
Revamp Navigation bar, change some text.

### PR DESCRIPTION
**Pull request by DanKGooGLy**

### CODE REVIEW

**Comment by mugman174** [comment]
ok lemme test dis

**Comment by mugman174** [comment]
ok it works

**Comment by mugman174** [comment]
but you forgot to edit the other .HTML files

**Comment by thewarsawpakt** [comment]
I'd prefer if we kept the branch names safe for work, and at least somewhat formal.

**Comment by mugman174** [comment]
true

**Comment by mugman174** [comment]
ok it works in testing - pushing to PrOd

**Pull request merged**
